import type { Internship } from './types';

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: '1',
    title: 'Backend Development (AICTE)',
    company: 'National Informatics Centre (NIC)',
    location: 'Bengaluru, KA',
    stipend: 55000,
    duration: '6 months',
    description: 'Work on core government microservices. This role involves designing and implementing REST APIs for national-level projects and ensuring platform scalability.',
    skills: ['Python', 'Go', 'Docker', 'Kubernetes', 'SQL', 'APIs'],
    companySize: 'Govt',
    industry: 'e-Governance',
    applyLink: 'https://internship.aicte-india.org/internship-details/backend-developer-1234.html',
  },
  {
    id: '2',
    title: 'Data Science Intern (PM Scheme)',
    company: 'NITI Aayog',
    location: 'New Delhi, DL',
    stipend: 40000,
    duration: '3 months',
    description: 'Analyze large policy datasets to extract meaningful insights for national strategy. Responsible for creating dashboards and generating reports.',
    skills: ['SQL', 'Python', 'Tableau', 'Pandas', 'Data Visualization', 'Statistics'],
    companySize: 'Govt',
    industry: 'Public Policy',
    applyLink: 'https://pmscheme.gov.in/internships/data-science-niti-5678.html',
  },
  {
    id: '3',
    title: 'Cyber Security Intern (AICTE)',
    company: 'DRDO',
    location: 'Hyderabad, TS',
    stipend: 45000,
    duration: '4 months',
    description: 'Assist in securing critical national infrastructure. Responsibilities include vulnerability assessment, penetration testing, and incident response.',
    skills: ['Cybersecurity', 'Networking', 'Linux', 'Penetration Testing'],
    companySize: 'Govt',
    industry: 'Defense',
    applyLink: 'https://internship.aicte-india.org/internship-details/cyber-security-drdo-9101.html',
  },
  {
    id: '4',
    title: 'UX/UI Design Intern (Digital India)',
    company: 'MyGov.in',
    location: 'Remote, India',
    stipend: 35000,
    duration: '3 months',
    description: 'Design intuitive and engaging user interfaces for citizen-facing applications. Create wireframes, mockups, and prototypes for web and mobile apps.',
    skills: ['Figma', 'Sketch', 'User Research', 'Prototyping', 'Accessibility'],
    companySize: 'Govt',
    industry: 'e-Governance',
    applyLink: 'https://pmscheme.gov.in/internships/ui-ux-mygov-1121.html',
  },
  {
    id: '5',
    title: 'VLSI Design Intern (AICTE)',
    company: 'Centre for Development of Advanced Computing (C-DAC)',
    location: 'Pune, MH',
    stipend: 50000,
    duration: '6 months',
    description: 'Contribute to the design and verification of semiconductor chips for Swadeshi Microprocessor initiatives. Work with Verilog/VHDL and EDA tools.',
    skills: ['Verilog', 'VHDL', 'EDA Tools', 'Semiconductor Physics'],
    companySize: 'Govt',
    industry: 'Semiconductors',
    applyLink: 'https://internship.aicte-india.org/internship-details/vlsi-cdac-3141.html',
  },
  {
    id: '6',
    title: 'AI/ML Intern (PM Scheme)',
    company: 'Indian Space Research Organisation (ISRO)',
    location: 'Bengaluru, KA',
    stipend: 65000,
    duration: '6 months',
    description: 'Work on cutting-edge research in satellite imagery analysis using computer vision. This role involves implementing and testing new models.',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'Computer Vision', 'Machine Learning'],
    companySize: 'Govt',
    industry: 'Aerospace',
    applyLink: 'https://pmscheme.gov.in/internships/ai-ml-isro-5161.html',
  },
];